apiVersion: v1
kind: Service
metadata:
  name: core-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    run: core
  ports:
    - name: enigmatick
      protocol: TCP
      port: 80
      targetPort: 8010
