apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: core
  name: core
  namespace: {{ .Values.namespace }}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: core
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: core
    spec:
      containers:
        - image: "localhost:32000/enigmatick-core:v{{ .Values.coreVersion }}"
          imagePullPolicy: Always
          name: core
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          env:
            - name: RUST_LOG
              value: "debug,html5ever=info"
            - name: ENIGMATICK_ROLE
              value: "server"
            - name: MEDIA_DIR
              value: "/srv/enigmatick/media"
            - name: ROCKET_DATABASES
              value: "{enigmatick={url=\"postgres://enigmatick@database-xeon.inst.cns.jdt.io/enigmatick\"}}"
            - name: ROCKET_PORT
              value: "8010"
            - name: ROCKET_ADDRESS
              value: "0.0.0.0"
            - name: DATABASE_URL
              value: "postgres://enigmatick@database-xeon.inst.cns.jdt.io/enigmatick"
            - name: SERVER_URL
              value: "https://enigmatick.social"
            - name: SERVER_NAME
              value: "enigmatick.social"
            - name: DEFAULT_AVATAR
              value: "icons/robot-mask.png"
            - name: SYSTEM_USER
              value: "system"
            - name: REGISTRATION_ENABLED
              value: "false"
            - name: REGISTRATION_APPROVAL_REQUIRED
              value: "true"
            - name: REGISTRATION_MESSAGE
              value: "service in development"
            - name: INSTANCE_CONTACT
              value: "justin@jdt.io"
            - name: INSTANCE_TITLE
              value: "Enigmatick"
            - name: INSTANCE_VERSION
              value: "0.0.1-alpha"
            - name: INSTANCE_SOURCE_URL
              value: "https://gitlab.com/enigmatick"
            - name: INSTANCE_DESCRIPTION
              value: "Enigmatick is an in-development service that will enable strong end-to-end privacy and provide users an open platform to publish both long-form articles and brief status updates."
            - name: SIGNING_OVERRIDE
              value: "false"
          volumeMounts:
          - mountPath: "/srv/enigmatick/media"
            name: media
          resources:
            requests:
              memory: "512Mi"
              cpu: "100m"
            limits:
              memory: "4Gi"
              cpu: "500m"
      volumes:
      - name: media
        persistentVolumeClaim:
          claimName: media
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
