apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-pv-tnas
  namespace: {{ .Values.namespace }}
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.42.128.6
    path: "/mnt/Main/k8s/enigmatick-media"
  mountOptions:
    - nfsvers=4
