apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-pv
  namespace: {{ .Values.namespace }}
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.37.15
    path: "/volume1/k8s/enigmatick-media"
  mountOptions:
    - nfsvers=4
