apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-tnas
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: ""
  accessModes: [ReadWriteMany]
  resources:
    requests:
      storage: 100Gi
  volumeName: media-pv-tnas
