apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: nginx
  name: nginx
  namespace: {{ .Values.namespace }}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      run: nginx
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: nginx
    spec:
      containers:
        - image: "localhost:32000/enigmatick-nginx:v{{ $.Chart.AppVersion }}"
          imagePullPolicy: Always
          name: nginx
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: "/srv/enigmatick/public/media"
            name: media
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "100m"
      volumes:
      - name: media
        persistentVolumeClaim:
          claimName: media
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
