apiVersion: v1
kind: Service
metadata:
  name: nginx-loadbalancer
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    run: nginx
  type: LoadBalancer
  externalTrafficPolicy: Local
