apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: rabbit
  name: rabbit
  namespace: {{ .Values.namespace }}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      run: rabbit
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: rabbit
    spec:
      containers:
        - image: rabbitmq:3-management
          imagePullPolicy: Always
          name: rabbit
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "100m"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
