apiVersion: v1
kind: Service
metadata:
  name: rabbit-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    run: rabbit
  ports:
    - name: rabbit
      protocol: TCP
      port: 5672
      targetPort: 5672
    - name: rabbit-management
      protocol: TCP
      port: 15672
      targetPort: 15672
  type: LoadBalancer
  externalTrafficPolicy: Local


