apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    run: web
  ports:
    - name: enigmatick
      protocol: TCP
      port: 80
      targetPort: 3000
